import { basePreset } from "@tradejs/base";
import { defineConfig } from "@tradejs/core/config";

export default defineConfig(basePreset, {
  runtime: {
    deployments: {
      production: {
        label: "Production",
        connectorName: "bybit",
        provider: "bybit",
        accountId: "bybit-default",
        enabled: true,
        strategies: {
          DoubleTap: {
            version: 5,
            enabled: true,
            config: {
              INTERVAL: "15",
              CLOSE_OPPOSITE_POSITIONS: false,
              BACKTEST_PRICE_MODE: "open",
              AI_ENABLED: true,
              AI_MODE: "gate",
              ML_ENABLED: false,
              ML_THRESHOLD: 0.1,
              MIN_AI_QUALITY: 4,
              FEE_PERCENT: 0.001,
              MAX_LOSS_VALUE: 1,
              MA_FAST: 14,
              MA_MEDIUM: 49,
              MA_SLOW: 50,
              OBV_SMA: 10,
              ATR: 14,
              ATR_PCT_SHORT: 7,
              ATR_PCT_LONG: 30,
              BB: 20,
              BB_STD: 2,
              MACD_FAST: 12,
              MACD_SLOW: 26,
              MACD_SIGNAL: 9,
              DOUBLETAP_PIVOT_LENGTH: 35,
              DOUBLETAP_PIVOT_TOLERANCE_PCT: 12,
              DOUBLETAP_TARGET_FIB_PCT: 180,
              DOUBLETAP_STOP_FIB_PCT: 0,
              DOUBLETAP_MIN_PATTERN_HEIGHT_PCT: 0.2,
              DOUBLETAP_MIN_PATTERN_HEIGHT_ATR: 1,
              DOUBLETAP_ATR_PERIOD: 14,
              DOUBLETAP_MIN_TAP_SPACING_BARS: 3,
              DOUBLETAP_MAX_PATTERN_AGE_BARS: 180,
              DOUBLETAP_MIN_LEG_SYMMETRY_RATIO: 0.25,
              DOUBLETAP_MIN_BREAKOUT_DISTANCE_ATR: 0.05,
              DOUBLETAP_MAX_BREAKOUT_DISTANCE_HEIGHT_RATIO: 0.8,
              DOUBLETAP_MAX_BREAKOUT_DISTANCE_PCT: 0.8,
              DOUBLETAP_ENTRY_MODE: "close_acceptance",
              DOUBLETAP_CONFIRMATION_MAX_BARS: 2,
              DOUBLETAP_MAX_ENTRY_CONFIRMATION_BARS: 0,
              DOUBLETAP_MAX_ENTRY_CONFIRMATION_BARS_LONG: 1,
              DOUBLETAP_MAX_ENTRY_CONFIRMATION_BARS_SHORT: 0,
              DOUBLETAP_MAX_BB_WIDTH_PCT: 0,
              DOUBLETAP_MAX_BB_WIDTH_PCT_LONG: 0,
              DOUBLETAP_MAX_BB_WIDTH_PCT_SHORT: 6,
              DOUBLETAP_RETEST_MAX_BARS: 4,
              DOUBLETAP_RETEST_TOLERANCE_ATR: 0.25,
              DOUBLETAP_EXIT_ON_OPPOSITE_PATTERN: true,
              LONG: {
                enable: true,
                direction: "LONG",
                minRiskRatio: 1.55,
              },
              SHORT: {
                enable: true,
                direction: "SHORT",
                minRiskRatio: 1.6,
              },
              UNIVERSE: "crypto",
              POLICY_PROFILE_ID: "crypto",
            },
          },
          TrendShift: {
            version: 1,
            enabled: true,
            config: {
              INTERVAL: "15",
              CLOSE_OPPOSITE_POSITIONS: false,
              BACKTEST_PRICE_MODE: "open",
              AI_ENABLED: true,
              AI_MODE: "gate",
              ML_ENABLED: false,
              ML_THRESHOLD: 0.1,
              MIN_AI_QUALITY: 5,
              FEE_PERCENT: 0.001,
              MAX_LOSS_VALUE: 1,
              MA_FAST: 14,
              MA_MEDIUM: 49,
              MA_SLOW: 50,
              OBV_SMA: 10,
              ATR: 14,
              ATR_PCT_SHORT: 7,
              ATR_PCT_LONG: 30,
              BB: 20,
              BB_STD: 2,
              MACD_FAST: 12,
              MACD_SLOW: 26,
              MACD_SIGNAL: 9,
              TRENDSHIFT_MULTIPLICATIVE_FACTOR: 4,
              TRENDSHIFT_SLOPE: 12,
              TRENDSHIFT_ATR_LENGTH: 150,
              TRENDSHIFT_WIDTH_PCT: 75,
              TRENDSHIFT_CONFIRM_FLIP_WITH_CLOSE: true,
              TRENDSHIFT_MIN_FLIP_DISTANCE_ATR: 0.15,
              TRENDSHIFT_MIN_SIGNAL_BODY_STRENGTH: 0.7,
              TRENDSHIFT_MIN_ADX: 25,
              TRENDSHIFT_MIN_ADX_SHORT: 40,
              TRENDSHIFT_STOP_ATR_BUFFER_MULT: 0,
              TRENDSHIFT_STOP_BUFFER_PCT: 0.06,
              TRENDSHIFT_TARGET_R_MULT: 1.2,
              TRENDSHIFT_TARGET_R_MULT_LONG: 1.2,
              TRENDSHIFT_TARGET_R_MULT_SHORT: 1,
              TRENDSHIFT_EXIT_ON_OPPOSITE_FLIP: true,
              TRENDSHIFT_OPPOSITE_EXIT_CONFIRMATION_BARS: 0,
              TRENDSHIFT_MAX_FIGURE_POINTS: 180,
              LONG: {
                enable: false,
                direction: "LONG",
                minRiskRatio: 1,
              },
              SHORT: {
                enable: true,
                direction: "SHORT",
                minRiskRatio: 0.8,
              },
              UNIVERSE: "crypto",
              POLICY_PROFILE_ID: "crypto",
            },
          },
        },
      },
    },
  },
});
