import { basePreset } from "@tradejs/base";
import { defineConfig } from "@tradejs/core/config";

const trendFollowForwardTickers = [
  "0GUSDT",
  "1000000BABYDOGEUSDT",
  "1000000MOGUSDT",
  "10000NEXUSDT",
  "10000SATSUSDT",
  "1000BONKUSDT",
  "1000BTTUSDT",
  "1000CATUSDT",
  "1000FLOKIUSDT",
  "1000LUNCUSDT",
  "1000NEIROCTOUSDT",
  "1000PEPEUSDT",
  "1000RATSUSDT",
  "1000TAGUSDT",
  "1000TOSHIUSDT",
  "1000TURBOUSDT",
  "1000XECUSDT",
  "1INCHUSDT",
  "2ZUSDT",
  "4USDT",
  "AUSDT",
  "AAVEUSDT",
  "ACEUSDT",
  "ACHUSDT",
  "ACTUSDT",
  "ACUUSDT",
  "ACXUSDT",
  "ADAUSDT",
  "AEROUSDT",
  "AEVOUSDT",
  "AGIUSDT",
  "AGLDUSDT",
  "AIGENSYNUSDT",
  "AIOUSDT",
  "AIOZUSDT",
  "AIXBTUSDT",
  "AKEUSDT",
  "AKTUSDT",
  "ALCHUSDT",
  "ALGOUSDT",
  "ALICEUSDT",
  "ALLOUSDT",
  "ALPINEUSDT",
  "ALTUSDT",
  "ANIMEUSDT",
  "ANKRUSDT",
  "APEUSDT",
  "APEXUSDT",
  "API3USDT",
  "APRUSDT",
  "APTUSDT",
  "ARUSDT",
  "ARBUSDT",
  "ARCUSDT",
  "ARIAUSDT",
  "ARKUSDT",
  "ARKMUSDT",
  "ARPAUSDT",
  "ARXUSDT",
  "ASPUSDT",
  "ASRUSDT",
  "ASTERUSDT",
  "ASTRUSDT",
  "ATUSDT",
  "ATHUSDT",
  "ATOMUSDT",
  "AUCTIONUSDT",
  "AVAUSDT",
  "AVAAIUSDT",
  "AVAXUSDT",
  "AVNTUSDT",
  "AWEUSDT",
  "AXLUSDT",
  "AXSUSDT",
  "AZTECUSDT",
  "BUSDT",
  "B2USDT",
  "B3USDT",
  "BABYUSDT",
  "BANUSDT",
  "BANANAUSDT",
  "BANANAS31USDT",
  "BANDUSDT",
  "BANKUSDT",
  "BARDUSDT",
  "BASEDUSDT",
  "BATUSDT",
  "BBUSDT",
  "BCHUSDT",
  "BEAMUSDT",
  "BEATUSDT",
  "BELUSDT",
  "BERAUSDT",
  "BICOUSDT",
  "BIGTIMEUSDT",
  "BILLUSDT",
  "BIOUSDT",
  "BIRBUSDT",
  "BLASTUSDT",
  "BLENDUSDT",
  "BLESSUSDT",
  "BLUAIUSDT",
  "BLURUSDT",
  "BMTUSDT",
  "BNBUSDT",
  "BNTUSDT",
  "BOBAUSDT",
  "BOMEUSDT",
  "BRUSDT",
  "BRETTUSDT",
  "BREVUSDT",
  "BROCCOLIUSDT",
  "BSBUSDT",
  "BSVUSDT",
  "BTCUSDT",
  "BTRUSDT",
  "BTWUSDT",
  "CUSDT",
  "C98USDT",
  "CAKEUSDT",
  "CAPUSDT",
  "CARVUSDT",
  "CASHCATUSDT",
  "CATIUSDT",
  "CCUSDT",
  "CELOUSDT",
  "CETUSUSDT",
  "CFGUSDT",
  "CFXUSDT",
  "CGPTUSDT",
  "CHILLGUYUSDT",
  "CHIPUSDT",
  "CHRUSDT",
  "CHZUSDT",
  "CKBUSDT",
  "CLANKERUSDT",
  "CLOUSDT",
  "COAIUSDT",
  "COMPUSDT",
  "COOKIEUSDT",
  "COREUSDT",
  "COTIUSDT",
  "COWUSDT",
  "CROUSDT",
  "CROSSUSDT",
  "CRVUSDT",
  "CTCUSDT",
  "CTRUSDT",
  "CVCUSDT",
  "CVXUSDT",
  "CYBERUSDT",
  "CYSUSDT",
  "DASHUSDT",
  "DATAUSDT",
  "DBRUSDT",
  "DEEPUSDT",
  "DEXEUSDT",
  "DIAUSDT",
  "DOGEUSDT",
  "DOLOUSDT",
  "DOODUSDT",
  "DOTUSDT",
  "DRIFTUSDT",
  "DUSKUSDT",
  "DYDXUSDT",
  "DYMUSDT",
  "EDENUSDT",
  "EDGEUSDT",
  "EDUUSDT",
  "EGLDUSDT",
  "EIGENUSDT",
  "ELSAUSDT",
  "ENAUSDT",
  "ENJUSDT",
  "ENSUSDT",
  "ENSOUSDT",
  "EPICUSDT",
  "ERAUSDT",
  "ESPUSDT",
  "ESPORTSUSDT",
  "ETCUSDT",
  "ETHUSDT",
  "ETHFIUSDT",
  "EULUSDT",
  "EVAAUSDT",
  "FUSDT",
  "FARTCOINUSDT",
  "FFUSDT",
  "FHEUSDT",
  "FIDAUSDT",
  "FIGHTUSDT",
  "FILUSDT",
  "FLOCKUSDT",
  "FLOWUSDT",
  "FLRUSDT",
  "FLUIDUSDT",
  "FLUXUSDT",
  "FOGOUSDT",
  "FOLKSUSDT",
  "FORMUSDT",
  "GALAUSDT",
  "GASUSDT",
  "GENIUSUSDT",
  "GIGGLEUSDT",
  "GLMUSDT",
  "GMTUSDT",
  "GMXUSDT",
  "GOATUSDT",
  "GPSUSDT",
  "GRAMUSDT",
  "GRASSUSDT",
  "GRIFFAINUSDT",
  "GRTUSDT",
  "GRVTUSDT",
  "GUNUSDT",
  "GWEIUSDT",
  "HUSDT",
  "HAEDALUSDT",
  "HANAUSDT",
  "HBARUSDT",
  "HEIUSDT",
  "HEMIUSDT",
  "HFTUSDT",
  "HIVEUSDT",
  "HMSTRUSDT",
  "HNTUSDT",
  "HOLOUSDT",
  "HOMEUSDT",
  "HUMAUSDT",
  "HYPEUSDT",
  "HYPERUSDT",
  "ICNTUSDT",
  "ICPUSDT",
  "ICXUSDT",
  "IDUSDT",
  "ILVUSDT",
  "IMXUSDT",
  "INUSDT",
  "INITUSDT",
  "INJUSDT",
  "INXUSDT",
  "IOUSDT",
  "IOSTUSDT",
  "IOTAUSDT",
  "IOTXUSDT",
  "IRYSUSDT",
  "JASMYUSDT",
  "JCTUSDT",
  "JELLYJELLYUSDT",
  "JSTUSDT",
  "JTOUSDT",
  "JUPUSDT",
  "KAIAUSDT",
  "KAITOUSDT",
  "KASUSDT",
  "KATUSDT",
  "KAVAUSDT",
  "KERNELUSDT",
  "KGENUSDT",
  "KITEUSDT",
  "KMNOUSDT",
  "KNCUSDT",
  "KSMUSDT",
  "LAUSDT",
  "LABUSDT",
  "LDOUSDT",
  "LIGHTUSDT",
  "LINEAUSDT",
  "LINKUSDT",
  "LITUSDT",
  "LPTUSDT",
  "LQTYUSDT",
  "LRCUSDT",
  "LSKUSDT",
  "LTCUSDT",
  "LUMIAUSDT",
  "LUNA2USDT",
  "LYNUSDT",
  "MUSDT",
  "MAGICUSDT",
  "MAGMAUSDT",
  "MANAUSDT",
  "MANTAUSDT",
  "MASKUSDT",
  "MAVUSDT",
  "MAVIAUSDT",
  "MEUSDT",
  "MEGAUSDT",
  "MELANIAUSDT",
  "MEMEUSDT",
  "MERLUSDT",
  "METUSDT",
  "METISUSDT",
  "MEWUSDT",
  "MINAUSDT",
  "MIRAUSDT",
  "MITOUSDT",
  "MMTUSDT",
  "MNTUSDT",
  "MOCAUSDT",
  "MONUSDT",
  "MOODENGUSDT",
  "MORPHOUSDT",
  "MOVEUSDT",
  "MOVRUSDT",
  "MTLUSDT",
  "MUBARAKUSDT",
  "MYXUSDT",
  "NAORISUSDT",
  "NEARUSDT",
  "NEOUSDT",
  "NEWTUSDT",
  "NIGHTUSDT",
  "NILUSDT",
  "NMRUSDT",
  "NOMUSDT",
  "NOTUSDT",
  "NXPCUSDT",
  "OUSDT",
  "OGUSDT",
  "OGNUSDT",
  "OKBUSDT",
  "ONDOUSDT",
  "ONGUSDT",
  "ONTUSDT",
  "OPUSDT",
  "OPENUSDT",
  "OPGUSDT",
  "OPNUSDT",
  "ORCAUSDT",
  "ORDERUSDT",
  "ORDIUSDT",
  "PARTIUSDT",
  "PEAQUSDT",
  "PENDLEUSDT",
  "PENGUUSDT",
  "PEOPLEUSDT",
  "PHAUSDT",
  "PHAROSUSDT",
  "PIEVERSEUSDT",
  "PIPPINUSDT",
  "PIXELUSDT",
  "PLAYSOUTUSDT",
  "PLUMEUSDT",
  "PNUTUSDT",
  "POLUSDT",
  "POLYXUSDT",
  "POPCATUSDT",
  "PORTALUSDT",
  "POWERUSDT",
  "POWRUSDT",
  "PRLUSDT",
  "PROMPTUSDT",
  "PROVEUSDT",
  "PTBUSDT",
  "PUFFERUSDT",
  "PUMPFUNUSDT",
  "PUNDIXUSDT",
  "PYTHUSDT",
  "QUSDT",
  "QNTUSDT",
  "QTUMUSDT",
  "RAREUSDT",
  "RAVEUSDT",
  "RAYDIUMUSDT",
  "REUSDT",
  "RECALLUSDT",
  "REDUSDT",
  "RENDERUSDT",
  "RESOLVUSDT",
  "REZUSDT",
  "RIVERUSDT",
  "RLCUSDT",
  "ROBOUSDT",
  "RONINUSDT",
  "ROSEUSDT",
  "RPLUSDT",
  "RSRUSDT",
  "RUNEUSDT",
  "RVNUSDT",
  "SUSDT",
  "SAFEUSDT",
  "SAGAUSDT",
  "SAHARAUSDT",
  "SANDUSDT",
  "SAPIENUSDT",
  "SCRTUSDT",
  "SEIUSDT",
  "SENTUSDT",
  "SHELLUSDT",
  "SHIB1000USDT",
  "SIGNUSDT",
  "SIRENUSDT",
  "SKLUSDT",
  "SKRUSDT",
  "SKYUSDT",
  "SKYAI1USDT",
  "SLPUSDT",
  "SLXUSDT",
  "SNTUSDT",
  "SNXUSDT",
  "SOLUSDT",
  "SOLAYERUSDT",
  "SOMIUSDT",
  "SONICUSDT",
  "SOONUSDT",
  "SOPHUSDT",
  "SOSOUSDT",
  "SPACEUSDT",
  "SPKUSDT",
  "SPORTFUNUSDT",
  "SPXUSDT",
  "SQDUSDT",
  "SSVUSDT",
  "STABLEUSDT",
  "STBLUSDT",
  "STEEMUSDT",
  "STGUSDT",
  "STOUSDT",
  "STORJUSDT",
  "STRKUSDT",
  "STXUSDT",
  "SUIUSDT",
  "SUNUSDT",
  "SUPERUSDT",
  "SUSHIUSDT",
  "SXTUSDT",
  "SYRUPUSDT",
  "TUSDT",
  "TAUSDT",
  "TACUSDT",
  "TAIKOUSDT",
  "TAOUSDT",
  "THEUSDT",
  "THETAUSDT",
  "TIAUSDT",
  "TLMUSDT",
  "TNSRUSDT",
  "TOWNSUSDT",
  "TRBUSDT",
  "TREEUSDT",
  "TRIAUSDT",
  "TRUMPUSDT",
  "TRUSTUSDT",
  "TRUTHUSDT",
  "TRXUSDT",
  "TURTLEUSDT",
  "TUTUSDT",
  "TWTUSDT",
  "UAIUSDT",
  "UBUSDT",
  "UMAUSDT",
  "UNIUSDT",
  "USUSDT",
  "USELESSUSDT",
  "USTCUSDT",
  "USUALUSDT",
  "VANAUSDT",
  "VANRYUSDT",
  "VELOUSDT",
  "VELODROMEUSDT",
  "VELVETUSDT",
  "VETUSDT",
  "VINEUSDT",
  "VIRTUALUSDT",
  "VVVUSDT",
  "WUSDT",
  "WALUSDT",
  "WAVESUSDT",
  "WAXPUSDT",
  "WCTUSDT",
  "WETUSDT",
  "WIFUSDT",
  "WLDUSDT",
  "WLFIUSDT",
  "WOOUSDT",
  "XAIUSDT",
  "XANUSDT",
  "XCNUSDT",
  "XDCUSDT",
  "XLMUSDT",
  "XMRUSDT",
  "XNYUSDT",
  "XPINUSDT",
  "XPLUSDT",
  "XRPUSDT",
  "XTZUSDT",
  "XVGUSDT",
  "XVSUSDT",
  "YBUSDT",
  "YFIUSDT",
  "YGGUSDT",
  "ZAMAUSDT",
  "ZBCNUSDT",
  "ZBTUSDT",
  "ZECUSDT",
  "ZENUSDT",
  "ZEREBROUSDT",
  "ZESTUSDT",
  "ZETAUSDT",
  "ZILUSDT",
  "ZKUSDT",
  "ZKCUSDT",
  "ZKPUSDT",
  "ZORAUSDT",
  "ZROUSDT",
  "ZRXUSDT",
] as string[];

const trendFollowForwardRuntimeConfig = {
  INTERVAL: "15",
  CLOSE_OPPOSITE_POSITIONS: false,
  BACKTEST_PRICE_MODE: "open",
  AI_ENABLED: true,
  AI_MODE: "gate",
  ML_ENABLED: false,
  ML_THRESHOLD: 0.1,
  MIN_AI_QUALITY: 4,
  FEE_PERCENT: 0.001,
  MAX_LOSS_VALUE: 1,
  MA_FAST: 14,
  MA_MEDIUM: 49,
  MA_SLOW: 50,
  OBV_SMA: 10,
  ATR: 14,
  ATR_PCT_SHORT: 7,
  ATR_PCT_LONG: 30,
  BB: 20,
  BB_STD: 2,
  MACD_FAST: 12,
  MACD_SLOW: 26,
  MACD_SIGNAL: 9,
  TRENDFOLLOW_PIVOT_LENGTH: 10,
  TRENDFOLLOW_MIN_BARS_BETWEEN_SIGNALS: 96,
  TRENDFOLLOW_ATR_LENGTH: 14,
  TRENDFOLLOW_ATR_MULT: 7,
  TRENDFOLLOW_SIGNAL_OFFSET_ATR: 0.35,
  TRENDFOLLOW_REQUIRE_STRUCTURE_BREAKOUT: true,
  TRENDFOLLOW_REQUIRE_TREND_ALIGNMENT: true,
  TRENDFOLLOW_REQUIRE_BENCHMARK_ALIGNMENT: true,
  TRENDFOLLOW_MIN_VOLUME_REL20: 1,
  TRENDFOLLOW_MIN_STRUCTURE_ACCEPTANCE_CLOSES: 0,
  TRENDFOLLOW_MIN_BREAKOUT_BODY_ATR: 0,
  TRENDFOLLOW_MIN_TREND_PERSISTENCE: 0,
  TRENDFOLLOW_MIN_TREND_PERSISTENCE_LONG: 0.5,
  TRENDFOLLOW_MIN_TREND_PERSISTENCE_SHORT: 0.5,
  TRENDFOLLOW_MAX_RSI: 0,
  TRENDFOLLOW_MAX_RSI_LONG: 75,
  TRENDFOLLOW_MAX_RSI_SHORT: 0,
  TRENDFOLLOW_MAX_BB_WIDTH_PCT: 0,
  TRENDFOLLOW_MAX_BB_WIDTH_PCT_LONG: 0,
  TRENDFOLLOW_MAX_BB_WIDTH_PCT_SHORT: 8,
  TRENDFOLLOW_MIN_BREAKOUT_DISTANCE_PCT: 2,
  TRENDFOLLOW_MIN_BREAKOUT_DISTANCE_PCT_LONG: 3,
  TRENDFOLLOW_MIN_BREAKOUT_DISTANCE_PCT_SHORT: 2,
  TRENDFOLLOW_MAX_BREAKOUT_DISTANCE_PCT: 0,
  TRENDFOLLOW_TARGET_R_MULT: 1.2,
  TRENDFOLLOW_TARGET_R_MULT_LONG: 1.4,
  TRENDFOLLOW_TARGET_R_MULT_SHORT: 1.2,
  TRENDFOLLOW_EXIT_ON_TRAIL_STOP: true,
  TRENDFOLLOW_EXIT_ON_OPPOSITE_SIGNAL: true,
  TRENDFOLLOW_MAX_FIGURE_POINTS: 180,
  LONG: {
    enable: true,
    direction: "LONG",
    minRiskRatio: 0.8,
  },
  SHORT: {
    enable: true,
    direction: "SHORT",
    minRiskRatio: 0.8,
  },
  UNIVERSE: "crypto",
};

export default defineConfig(basePreset, {
  runtime: {
    deployments: {
      "trendfollow-forward-loss-guard-20260818": {
        label: "TrendFollow Forward Loss Guard 20260818",
        connectorName: "bybit",
        provider: "bybit",
        accountId: "bybit-default",
        enabled: true,
        tickers: trendFollowForwardTickers,
        strategies: {
          TrendFollow: {
            version: 2,
            enabled: true,
            config: trendFollowForwardRuntimeConfig,
          },
        },
      },
      production: {
        label: "Production",
        connectorName: "bybit",
        provider: "bybit",
        accountId: "bybit-default",
        enabled: true,
        strategies: {
          DoubleTap: {
            version: 6,
            enabled: true,
            config: {
              INTERVAL: "15",
              CLOSE_OPPOSITE_POSITIONS: false,
              BACKTEST_PRICE_MODE: "open",
              AI_ENABLED: true,
              AI_MODE: "gate",
              ML_ENABLED: false,
              ML_THRESHOLD: 0.1,
              MIN_AI_QUALITY: 4,
              FEE_PERCENT: 0.001,
              MAX_LOSS_VALUE: 1,
              MA_FAST: 14,
              MA_MEDIUM: 49,
              MA_SLOW: 50,
              OBV_SMA: 10,
              ATR: 14,
              ATR_PCT_SHORT: 7,
              ATR_PCT_LONG: 30,
              BB: 20,
              BB_STD: 2,
              MACD_FAST: 12,
              MACD_SLOW: 26,
              MACD_SIGNAL: 9,
              DOUBLETAP_PIVOT_LENGTH: 35,
              DOUBLETAP_PIVOT_TOLERANCE_PCT: 12,
              DOUBLETAP_TARGET_FIB_PCT: 180,
              DOUBLETAP_STOP_FIB_PCT: 0,
              DOUBLETAP_MIN_PATTERN_HEIGHT_PCT: 0.2,
              DOUBLETAP_MIN_PATTERN_HEIGHT_ATR: 1,
              DOUBLETAP_ATR_PERIOD: 14,
              DOUBLETAP_MIN_TAP_SPACING_BARS: 3,
              DOUBLETAP_MAX_PATTERN_AGE_BARS: 180,
              DOUBLETAP_MIN_LEG_SYMMETRY_RATIO: 0.25,
              DOUBLETAP_MIN_BREAKOUT_DISTANCE_ATR: 0.05,
              DOUBLETAP_MAX_BREAKOUT_DISTANCE_HEIGHT_RATIO: 0.8,
              DOUBLETAP_MAX_BREAKOUT_DISTANCE_PCT: 0.8,
              DOUBLETAP_ENTRY_MODE: "close_acceptance",
              DOUBLETAP_CONFIRMATION_MAX_BARS: 2,
              DOUBLETAP_MAX_ENTRY_CONFIRMATION_BARS: 0,
              DOUBLETAP_MAX_ENTRY_CONFIRMATION_BARS_LONG: 1,
              DOUBLETAP_MAX_ENTRY_CONFIRMATION_BARS_SHORT: 0,
              DOUBLETAP_MAX_BB_WIDTH_PCT: 0,
              DOUBLETAP_MAX_BB_WIDTH_PCT_LONG: 0,
              DOUBLETAP_MAX_BB_WIDTH_PCT_SHORT: 6,
              DOUBLETAP_RETEST_MAX_BARS: 4,
              DOUBLETAP_RETEST_TOLERANCE_ATR: 0.25,
              DOUBLETAP_EXIT_ON_OPPOSITE_PATTERN: true,
              LONG: {
                enable: true,
                direction: "LONG",
                minRiskRatio: 1.55,
              },
              SHORT: {
                enable: true,
                direction: "SHORT",
                minRiskRatio: 1.6,
              },
              UNIVERSE: "crypto",
              POLICY_PROFILE_ID: "crypto",
            },
          },
          TrendShift: {
            version: 2,
            enabled: true,
            config: {
              INTERVAL: "15",
              CLOSE_OPPOSITE_POSITIONS: false,
              BACKTEST_PRICE_MODE: "open",
              AI_ENABLED: true,
              AI_MODE: "gate",
              ML_ENABLED: false,
              ML_THRESHOLD: 0.1,
              MIN_AI_QUALITY: 5,
              FEE_PERCENT: 0.001,
              MAX_LOSS_VALUE: 1,
              MA_FAST: 14,
              MA_MEDIUM: 49,
              MA_SLOW: 50,
              OBV_SMA: 10,
              ATR: 14,
              ATR_PCT_SHORT: 7,
              ATR_PCT_LONG: 30,
              BB: 20,
              BB_STD: 2,
              MACD_FAST: 12,
              MACD_SLOW: 26,
              MACD_SIGNAL: 9,
              TRENDSHIFT_MULTIPLICATIVE_FACTOR: 4,
              TRENDSHIFT_SLOPE: 12,
              TRENDSHIFT_ATR_LENGTH: 150,
              TRENDSHIFT_WIDTH_PCT: 75,
              TRENDSHIFT_CONFIRM_FLIP_WITH_CLOSE: true,
              TRENDSHIFT_MIN_FLIP_DISTANCE_ATR: 0.15,
              TRENDSHIFT_MIN_SIGNAL_BODY_STRENGTH: 0.7,
              TRENDSHIFT_MIN_ADX: 25,
              TRENDSHIFT_MIN_ADX_SHORT: 40,
              TRENDSHIFT_STOP_ATR_BUFFER_MULT: 0,
              TRENDSHIFT_STOP_BUFFER_PCT: 0.06,
              TRENDSHIFT_TARGET_R_MULT: 1.2,
              TRENDSHIFT_TARGET_R_MULT_LONG: 1.2,
              TRENDSHIFT_TARGET_R_MULT_SHORT: 1,
              TRENDSHIFT_EXIT_ON_OPPOSITE_FLIP: true,
              TRENDSHIFT_OPPOSITE_EXIT_CONFIRMATION_BARS: 0,
              TRENDSHIFT_MAX_FIGURE_POINTS: 180,
              LONG: {
                enable: false,
                direction: "LONG",
                minRiskRatio: 1,
              },
              SHORT: {
                enable: true,
                direction: "SHORT",
                minRiskRatio: 0.8,
              },
              UNIVERSE: "crypto",
              POLICY_PROFILE_ID: "crypto",
            },
          },
        },
      },
    },
  },
});
