import type { RuntimeStrategyDeclaration } from "@tradejs/types";

export const trendShiftRuntime = {
  enabled: true,
  config: {
    INTERVAL: "15",
    CLOSE_OPPOSITE_POSITIONS: false,
    BACKTEST_PRICE_MODE: "open",
    AI_ENABLED: true,
    AI_MODE: "gate",
    ML_ENABLED: false,
    ML_THRESHOLD: 0.1,
    MIN_AI_QUALITY: 5,
    FEE_PERCENT: 0.001,
    MAX_LOSS_VALUE: 1,
    MA_FAST: 14,
    MA_MEDIUM: 49,
    MA_SLOW: 50,
    OBV_SMA: 10,
    ATR: 14,
    ATR_PCT_SHORT: 7,
    ATR_PCT_LONG: 30,
    BB: 20,
    BB_STD: 2,
    MACD_FAST: 12,
    MACD_SLOW: 26,
    MACD_SIGNAL: 9,
    TRENDSHIFT_MULTIPLICATIVE_FACTOR: 4,
    TRENDSHIFT_SLOPE: 12,
    TRENDSHIFT_ATR_LENGTH: 150,
    TRENDSHIFT_WIDTH_PCT: 75,
    TRENDSHIFT_CONFIRM_FLIP_WITH_CLOSE: true,
    TRENDSHIFT_MIN_FLIP_DISTANCE_ATR: 0.15,
    TRENDSHIFT_MIN_SIGNAL_BODY_STRENGTH: 0.7,
    TRENDSHIFT_MIN_ADX: 25,
    TRENDSHIFT_MIN_ADX_SHORT: 40,
    TRENDSHIFT_STOP_ATR_BUFFER_MULT: 0,
    TRENDSHIFT_STOP_BUFFER_PCT: 0.06,
    TRENDSHIFT_TARGET_R_MULT: 1.2,
    TRENDSHIFT_TARGET_R_MULT_LONG: 1.2,
    TRENDSHIFT_TARGET_R_MULT_SHORT: 1,
    TRENDSHIFT_EXIT_ON_OPPOSITE_FLIP: true,
    TRENDSHIFT_OPPOSITE_EXIT_CONFIRMATION_BARS: 0,
    TRENDSHIFT_MAX_FIGURE_POINTS: 180,
    LONG: {
      enable: false,
      direction: "LONG",
      minRiskRatio: 1,
    },
    SHORT: {
      enable: true,
      direction: "SHORT",
      minRiskRatio: 0.8,
    },
    UNIVERSE: "crypto",
    POLICY_PROFILE_ID: "crypto",
  },
} satisfies RuntimeStrategyDeclaration;
